version: '3'

services:
  api:
    container_name: deliveryapp-api
    image: denlysenko/deliveryapp-api
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
      - postgres

  mongodb:
    container_name: mongodb
    image: mongo:3.4
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  postgres:
    container_name: postgres
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    external: true
  mongo_data:
    external: true
